homework9 - ready
oleglestat/homework pull request #10
Opened 2023-12-11 10:30 UTC by oleglestat

2023-12-14 08:26 UTC, myroslav-kolomiiets requested changes

2023-12-14 08:26 UTC, myroslav-kolomiiets commented on homework9/weatherApp.js
> +        let response = await fetch( url );
fetch завжди треба обгортати в try...catch

2023-12-14 08:26 UTC, myroslav-kolomiiets commented on homework9/weatherApp.js
> +        this.isLoading = false;
```suggestion
try {
        let response = await fetch( url );
        let data = await response.json();
        console.log( data );
        this.updateDOM( data );
        } catch(error) {
        throw new Error(error)
        } finally {
        this.isLoading = false;
        }
```

2023-12-14 10:39 UTC, oleglestat commented on homework9/weatherApp.js
> +        let response = await fetch( url );
для цього я використовую        
`weatherApp.fetchData().catch(console.error);
`

2023-12-19 16:25 UTC, myroslav-kolomiiets approved these changes

2023-12-19 16:25 UTC, merged