homework2.js - done
oleglestat/homework pull request #3
Opened 2023-10-09 16:54 UTC by oleglestat

2023-10-09 18:31 UTC, myroslav-kolomiiets requested changes

2023-10-09 18:31 UTC, myroslav-kolomiiets commented on homework2.js
> +function durationBetweenDates( date1, date2, units='seconds' ) {
Для date1 та date2 також мають бути дефолтні значення

2023-10-09 18:31 UTC, myroslav-kolomiiets commented on homework2.js
> +			console.log( `${result/1000/60/60} hours` );
Все що дублюється, тобто /1000 також можна і треба винести в 13 рядок

І ще, функція має повертати значення, а не виводити його в консоль, тобто тут має бути:
```suggestion
			return `${result/1000/60/60} hours`;
```

2023-10-09 18:31 UTC, myroslav-kolomiiets commented on homework2.js
> +function optimizer(data) {
Рішення відповідне умові, але воно змінює початковий об'єкт, рекомендую подумати над рішенням яке буде повертати новий об'єкт з потрібним форматуванням

2023-10-09 18:59 UTC, oleglestat commented on homework2.js
> +function optimizer(data) {
В функції створюється новий обʼєкт, якщо вивести в консоль 2 обʼєкти то бачимо що перший не змінився
console.log(priceData); // { Apples: '23.4', BANANAS: '48', oRAngGEs: '48.7584', 'Pine Apple': '233.73'}
console.log(updatedPriceData) // {apples: '23.40', bananas: '48.00', oranges: '48.76', 'pine apple': '233.73'}

2023-10-09 20:18 UTC, oleglestat commented on homework2.js
> +function durationBetweenDates( date1, date2, units='seconds' ) {
Done

2023-10-09 20:20 UTC, oleglestat commented on homework2.js
> +			console.log( `${result/1000/60/60} hours` );
Done

2023-10-12 13:15 UTC, myroslav-kolomiiets approved these changes

2023-10-12 13:15 UTC, myroslav-kolomiiets commented on homework2.js
> +function optimizer(data) {
Все вірно, моя помилка, пропустив що створюєете новий об'єкт і заповнюєте його в циклі.

2023-10-16 09:23 UTC, merged