homework5.js - done
oleglestat/homework pull request #6
Opened 2023-11-07 19:07 UTC by oleglestat

2023-11-09 08:53 UTC, myroslav-kolomiiets requested changes

2023-11-09 08:53 UTC, myroslav-kolomiiets commented on homework5/selectors.js
> +const textElement = document.querySelector( '#headerTwo' );
querySelector абсолютно достатньо для вирішення всіх подібних задач, згоден і сам рекомендую

але по умові конкретної задачі, треба використати різні методи, в навчальних цілях

2023-11-09 08:53 UTC, myroslav-kolomiiets commented on homework5/script.js
> +			body.classList.add( 'dark' );
Оскільки реалізація являє собою тільки один клас, тоді його можна тоглити, а не додавати і прибирати
`classList.toggle
`

2023-11-09 08:53 UTC, myroslav-kolomiiets commented on homework5/script.js
> +		button.textContent = buttonStatus
Бажано розділяти логіку по компонентах, те що стосується кнопки, задавати в відповідній функції

2023-11-09 08:53 UTC, myroslav-kolomiiets commented on homework5/script.js
> +		button.textContent = buttonStatus
А те що сторінки - в цій

2023-11-12 14:05 UTC, oleglestat commented on homework5/script.js
> +			body.classList.add( 'dark' );
Тоглити при цій реалізації не вийде - якщо сторінка завантажується з кнопкою в статусі 'turn on' то я автоматично додаю клас 'dark'. Тобто я тут обробляю момент перезавантаження сторінки

2023-11-12 16:27 UTC, oleglestat commented on homework5/script.js
> +			body.classList.add( 'dark' );
Зробив

2023-11-12 16:27 UTC, oleglestat commented on homework5/script.js
> +		button.textContent = buttonStatus
переробив

2023-11-14 12:32 UTC, myroslav-kolomiiets approved these changes

2023-11-14 12:37 UTC, merged